--!strict
--[[
	
	Copyright (c) 2025 bytenand (Roblox) & y29r (GitHub). All rights reserved.
	
	By using this product, you agree to the terms provided in the original repository.
	
	Unauthorized use, modification, distribution, or commercial use of this product
	is strictly prohibited without explicit written permission from the copyright holder.
	
	This product is protected under copyright law and is subject to DMCA enforcement.
	Illegal copies or repeated violations may result in further action.
	
	If this product is being used as part of a commissioned or collaborative project,
	permission has been granted to modify the product for that project only.
	Redistribution remains prohibited.
	
]]